name: Deploy Nuxt 3 to Pages

on:
  push:
    branches: ["main"]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  install:
    name: Install node modules
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 16
      
      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: pnpm i

  generate:
    name: Nuxt generate
    needs: install
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'pnpm'
          node-version: 16
      
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: modules-${{ hashFiles('pnpm-lock.yaml') }}
     
      - name: Nuxt Generate
        run: pnpm generate
  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./.output/public
